apiVersion: v1
kind: Service
metadata:
  name: sentinel-tunnel
  labels:
    app: sentinel-tunnel
spec:
  ports:
  - port: 26379
    targetPort: 26379
    protocol: TCP
  selector:
    app: sentinel-tunnel
